### ISSUE TITLE
Error when cancelling Convert to Collider

### ISSUE THREAD

**Issue by Weisl** [Weisl/Collider-Tools#165]

**Comment by Weisl** [comment]
location: <unknown location>:-1
Error: Python: Traceback (most recent call last):
  File "C:\Users\weisl\Documents\Github_blender_scripts\addons\collider_tools\operators\conversion_operators.py", line 55, in modal
    status = super().modal(context, event)
  File "C:\Users\weisl\Documents\Github_blender_scripts\addons\collider_tools\operators\add_bounding_primitive.py", line 774, in modal
    set_physics_material(obj, bpy.data.materials[mat])
  File "C:\Users\weisl\Documents\Github_blender_scripts\addons\collider_tools\pyshics_materials\material_functions.py", line 36, in set_physics_material
    if physics_material_name and physics_material_name in bpy.data.materials:
TypeError: bpy_prop_collection.__contains__: expected a string or a tuple of strings

location: <unknown location>:-1

**Comment by Weisl** [comment]
Can't reproduce
