### ISSUE TITLE
Error when: USE MODIFIERS for LOOSE MESH

### ISSUE THREAD

**Issue by Weisl** [Weisl/Collider-Tools#421]
![image](https://github.com/Weisl/Collider-Tools/assets/6353016/8f6e464c-c5b9-4316-8072-da7733f594fd)
```

Error: Python: Traceback (most recent call last):
  File "C:\Users\weisl\OneDrive\Dokumente\GitHub\scripts\addons\collider_tools\collider_shapes\add_bounding_cylinder.py", line 249, in modal
    self.execute(context)
  File "C:\Users\weisl\OneDrive\Dokumente\GitHub\scripts\addons\collider_tools\collider_shapes\add_bounding_cylinder.py", line 371, in execute
    bpy.ops.object.mode_set(mode='OBJECT')
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\scripts\modules\bpy\ops.py", line 113, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Operator bpy.ops.object.mode_set.poll() Context missing active object
```

**Comment by Weisl** [comment]
Broken for:
- [ ] Cylinder
- [ ] Convex
- [ ] Mesh
